### ISSUE TITLE
Setup a simple Discord bot that communicate with OpenAI using interactions.py

### ISSUE THREAD

**Issue by nqngo** [bifrostlab/llm-assistant#1]
Create a simple Discord bot that leverage OpenAI API for members of VAIT. The preferred command we are supporting:

```bash
/ask model:{gpt3|gpt4} question
```

Essentially we are replicating ChatGPT directly in Discord. The preferred framework is `interactions.py` in Python:
https://interactionspy.readthedocs.io/en/latest/index.html

**Comment by nqngo** [comment]
This issue should be broken down into smaller issues by members of the issue.

**Comment by nqngo** [comment]
@HenryNg101 any update on this please?

**Comment by phattantran1997** [comment]
Hi @nqngo  and @HenryNg101 , I tried to write a demo Bot but not using Python instead of nodejs. But I  will change to the Python syntax soon. Hope that can help.

**Comment by rodonguyen** [comment]
Hey Team, use the new docs with v5.x syntax: https://interactions-py.github.io/interactions.py/Guides/

**Comment by rodonguyen** [comment]
@nqngo @HenryNg101 Is this issue done in https://github.com/bifrostlab/llm-assistant/pull/9?

If not, we should redefine this issue

**Comment by keduong33** [comment]
This one is linked to #25

**Comment by rodonguyen** [comment]
It's done as of #34
