### ISSUE TITLE
Enable Discord bot to interact with OpenAI API

### ISSUE THREAD

**Issue by rodonguyen** [bifrostlab/llm-assistant#25]
- Integrate OpenAI bot (via its API) to the current discord bot
- Also utilise LiteLM để act as a scheduler, tránh tình trạng response lâu (`await ctx.defer()`) hay nhiều requests làm đơ bot

**Comment by hungdtrn** [comment]
Cái này close dược rồi nhỉ?

**Comment by nqngo** [comment]
I don't think we put a high priority on using OpenAI to response to the users. Remember OpenAI resource is not something we can completely use for free and is at the good will of the donated key.

It is fine to keep the response delayed and use the local LLM model as I can try getting us more funding on that aspect to improve the model responsiveness. I do not have that luxury with OpenAI models.
