### ISSUE TITLE
Add ENV variables validation before running the discord bot

### ISSUE THREAD

**Issue by rodonguyen** [bifrostlab/llm-assistant#36]
The idea is to make sure the bot application has all of the required environment variables before running. If it doesn't, throw an error and log an error message.

See this example in VAIT Discord Bot:
https://github.com/viet-aus-it/vait-discord-bot/blob/d82011e4b856d9a9512467beab9c85fb9df46780/src/utils/loadEnv/index.ts#L30 

```ts
function loadenv() {
  const config = dotenv.config();
  dotenvExpand.expand(config);

  const validatedEnv = configSchema.safeParse(process.env); // <= Validate the environment
  if (!validatedEnv.success) {
    console.error(`Error loading environment details. ${validatedEnv.error.message}`);
    throw new Error('INVALID CONFIG!', { cause: validatedEnv.error.issues });
  }
}
```

We can have a look at running this via [`pydantic`](https://docs.pydantic.dev/)

Reference:
- https://docs.pydantic.dev/latest/concepts/pydantic_settings/
- https://medium.com/@mahimamanik.22/environment-variables-using-pydantic-ff6ccb2b8976

**Comment by NguyenQuang-10** [comment]
I tried using Pydantic for validation, it works but MyPy are throwing errors, I need some assistance on this as I'm new to both Pydantic and MyPy:

Validation code:
```
class Settings(BaseSettings):
  model_config = SettingsConfigDict(env_file="../../.env", env_file_encoding="utf-8")

  DISCORD_BOT_TOKEN: str
  DISCORD_GUILD_ID: str
  AI_SERVER_URL: str = Field(default="http://localhost:8000")
  OPENAI_API_KEY: str

settings = Settings()
```


MyPy CI error:
![Image](https://github.com/bifrostlab/llm-assistant/assets/66954117/7b15fa59-3d6e-43ae-b56f-83526a3c42b7)

@rodonguyen
