### ISSUE TITLE
Write a suite of functional tests for the Discordbot

### ISSUE THREAD

**Issue by nqngo** [bifrostlab/llm-assistant#4]
Create a suite of functional tests to test the Discordbot functionality. You can write the tests without writing the codes first and aid the dev team with their development.

Essentially you already know the input and output, use mock, asyncio, and pytest to create a test of functional tests for the codes.

For example, imagine the following command get called:

```bash
/ask model:gpt4 prompt:"What is the capital of France?"
```

The LLMBot will watch for the slash command into the main function and call the hypothetical following function:

```bash
main --> prompt_gpt4(string)
```

You can write the set of functional testing that the prompt_gpt4 will get call and return a set of string with the answers to simulate the user experience.

**Comment by samhwang** [comment]
This is already covered by #58
