### ISSUE TITLE
Strange/unrelated questions and answers in the Bot response

### ISSUE THREAD

**Issue by rodonguyen** [bifrostlab/llm-assistant#46]
IIRC, I asked `phi`:
```
what model are you? 3.5 or 4?
```

Its response not only contains the answer I need but also the weird answers to other questions that I don't ask:
![image](https://github.com/bifrostlab/llm-assistant/assets/30222384/6ca1c406-8753-476e-8c02-e755d8a911aa)

I log the bug here in case someone encounters this again. Then, we will investigate.

**Comment by rodonguyen** [comment]
chatted with the AI Engineers, could be hallucinations from training Ollama/phi.

**Comment by hungdtrn** [comment]
We can potentially add stop word at "Question:" so that the AI will stop when it see "Question:" in the generated answer
