### ISSUE TITLE
About Python Environment Mangagement

### ISSUE THREAD

**Issue by hungdtrn** [bifrostlab/llm-assistant#5]
I believe we should have a shared python environment for developing this project. What tools are you familiar with for managing Python environments? I have experience with both Conda, but I'm open to other options like venv.

**Comment by dacphuc1993** [comment]
I vote for Conda.

**Comment by nqngo** [comment]
I don't think we need Conda, and recommend a virtualenv, poetry or just package the applicant in a docker devcontainer.

Conda is pretty comprehensive and work exceedingly well for pytorch or tensorflow. It shines where you need dependencies with hardware C integration.

We are only building APIs. Conda is too bloated for this purpose. Can just keep it simple and use normal Python other env management.

**Comment by hungdtrn** [comment]
Thanks a @nqngo , I've just checked Poetry and found that it is pretty simple and easier to use than Conda. I've setup Poetry and writing documents for how to use it.
